### ISSUE TITLE
Only body bone appears after adding rig

### ISSUE THREAD

**Issue by HansEberhart** [digicreatures/rigacar#9] opened 2019-06-18 18:56 UTC
Hi, 

first of all, thanks very much for developing this addon and the very nice documentation and tutorials. 

I tried to follow your tutorial but when I try to add a rig it only spawns the body bone but not the bones for the wheels or the breaks. Any ideas?

I'm on latest blender 2.8 with the latest version of your addon.

![Capture](https://user-images.githubusercontent.com/30523862/59711541-95fa1180-920b-11e9-8e7a-764d55ebe5d4.JPG)

Cheers!

**Comment by spoonless** [comment] 2019-06-18 20:15
This issue has just appeared on the last build of Blender. Sorry for that but I am pretty sure it is a bug from Blender 2.80 or some kind of side effect from the latest developments.
It could be fixed by blender developers themselves on next builds. I need some time to figure out the problem and, if necessary, report a bug on Blender 2.80.
Thank you for sharing this

As a workaround you can do things manually :
* deselect all objects on your scene
* add the armature and use the panel to add necessary deformation bones
* edit the armature and move each bone to the right position
* parent each reference object to the correct bone (for instance parent the body to the bone DEF-Body)
* then click on generate

**Comment by HansEberhart** [comment] 2019-06-18 20:52
Thanks for the fast help, it works well now!

**Comment by spoonless** [comment] 2019-06-19 08:39
Bug still present. I must investigate about it

**Comment by spoonless** [comment] 2019-07-31 14:15
bug fix in Blender 2.80

**Closed by spoonless** 2019-07-31 14:15 UTC
Labels: bug

**Comment by alexgorban** [comment] 2020-11-30 07:03
The issue is still present in blender 2.91 and in 2.83a. I tried to rig several cars a number of times, some of them were rigged correctly. But others are missing bones for wheels. While wheels themselves were correctly recognized (you can change their location via rigcar menu, corresponding bones are refereed as parent bones their mesh objects).
